# #################################################
# Fallback/global configuration if there is no configuration in the content repository defined
# for the respective site.
# #################################################

# DeepL API key
#deepl.apiKey=

# Optional proxy URL
#deepl.proxyUrl=

# Optional DeepLClientOptions: deepl.client-options.*
# see https://github.com/DeepLcom/deepl-java/blob/main/deepl-java/src/main/java/com/deepl/api/DeepLClientOptions.java
# and https://github.com/DeepLcom/deepl-java/blob/main/deepl-java/src/main/java/com/deepl/api/TranslatorOptions.java
# e.g.
# Timeout (in Spring Duration format)
deepl.client-options.timeout=30s

# Optional TextTranslationOptions: deepl.text-translation-options.*
# see https://github.com/DeepLcom/deepl-java/blob/main/deepl-java/src/main/java/com/deepl/api/TextTranslationOptions.java
# e.g.
# Model Type (in Spring Duration format)
#deepl.text-translation-options.model-type=prefer_quality_optimized
# or IgnoreTags
#deepl.text-translation-options.ignore-tags=tag1,tag2

